name: my_first_workflow
# to get a trigger on every push in the rep in any branch
on: push
# define jobs in workflow
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running single command in job1
        run: echo "Hi this is my first Github workflow using YAML"

      - name: checking os release for github hosted runner
        run: cat /etc/os-release

      - name: checking whoami command
        run: whoami
