name: my_first_workflow_actions
# to get a trigger push every minute
on: 
  push: # these push only work following brachnes
    branches: 
       - main
  pull_request:   # so only trigger when request from main bracher
    branches:   
      - main
env:
  ENV_TYPE: DEV
  APP_USER: thinknyx
  APP_PORT: 80

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          pwd
          ls -ltr
          hostname
      - name:  step 2
        uses: actions/checkout@v7.0.0
      - name: step 3
        run: |
          echo 'pwd' >> myartifact.txt  # file created and pwd written in there
          mkdir artifacts
          echo 'ls -tlr' >> artifacts/list.txt
          echo 'hostname' >> artifacts/hostname.txt
      - name: upload single file
        uses: actions/upload-artifact@v7  # actions got from github marketplace
        with:
          name: single_file
          path: ./myartifact.txt
      
  jobs2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: checking current directory
        run: |
          pwd
          ls -ltr
      - name: downlaod single file artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: single_file
      - name: Reffering environment varaibale
        run: |
          echo "[INFO] Running deployment for $ENV_TYPE with user $APP_USER"
          echo "[INFO] once deployement applicaiton is accessible on port $APP_PORT"
      - name: Reffering repository secrets
        run:  |
          echo "[INFO] application poassword is ${{secrets.APP_PASSWORD}}"
      - name: checking current directory post download
        run: |
          pwd
          ls -ltr

    
      
    
      
          
        
      

    
