name: my_first_workflow_actions
# to get a trigger push every minute
on: 
  push:

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          pwd
          ls -ltr
          hostname
      - name:  step 2
        uses: actions/checkcout@v7.0.0
      - name: step 3
        run: |
          pwd
          ls -tlr
          hostname
          
        
      

    
